// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Task { id: number, name: string, color: string, start_date: number, end_date: number, description: string, }