// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Preset } from "./Preset";
import type { Task } from "./Task";

export interface TaskModalI {
    loadedTask: Task;
    presets: Array<Preset>;
}
