// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresetI } from "./PresetI";
import type { TaskI } from "./TaskI";

export interface TaskModalI { task: TaskI, presets: Array<PresetI>, }